# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            21    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build
        run: ./gradlew build
      - name: SHA256 Checksum
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        run: sha256sum build/libs/* >> sha256.txt
      - name: Publish Checksum Output to Summary
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        run: |
          {
            echo "### Artifact SHA256"
            echo '```terraform'
            cat sha256.txt
            echo '```'
            echo "### Gradle Summary"
          } >> $GITHUB_STEP_SUMMARY
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v6
        with:
          name: Artifacts
          path: build/libs/
